### ISSUE TITLE
Не работают Инвестиции в оффлайн режиме

### ISSUE THREAD

**Issue by EwgenpProsto** [SnaiCrys/BUG-TRACKER#121]
Вкладывал в Гейклуб первоначально 2000$
22:00 закинул до 4000$ и в прибыли уже было 80$
23:36  прибыли 320$
0:10 ушел спать прибыль 400$
Зашел на сервер в 11:30, прибыль = 400$

**Comment by SnaiCrys** [comment]
И не должны работать
