### ISSUE TITLE
анимация срабатывает и в нескольких метрах от заправки

### ISSUE THREAD

**Issue by GomeshRu** [SnaiCrys/BUG-TRACKER#130]
![20180315174747_1](https://user-images.githubusercontent.com/37335697/37559433-19b7a7fa-2a37-11e8-9004-cba41acea51a.jpg)

и при этом реально заправляет

**Comment by SnaiCrys** [comment]
ничего не понятно

**Comment by SnaiCrys** [comment]
Это случайно не дубликат этого бага https://github.com/SnaiCrys/BUG-TRACKER/issues/64 ?

**Comment by SnaiCrys** [comment]
добавил проверку на дистанцию
