### ISSUE TITLE
Дублирование цены при выкладывании товара в молл

### ISSUE THREAD

**Issue by Fl4tl1ne** [SnaiCrys/BUG-TRACKER#134]
Если в указанной цене есть 0 после точки (напр. 7.06 $), то в молле отображается цена на 1 цент больше - 7.07 $. При этом другой игрок не может выложить товар ни по 7.06 $, ни по 7.07$.

**Comment by SnaiCrys** [comment]
а по 7,08?

**Comment by ParadoxShow** [comment]
по 7.08 округлит до 7.09. По 7.09 - до 7.10 . Если по 7.10 и выше - всё ок. трабл именно если ноль идет сразу после запятой (например: 7.01)

**Comment by SnaiCrys** [comment]
думаю не смогу это поправить, потому что 7.08 на самом деле 7.085454654684645648655555555555

**Comment by Fl4tl1ne** [comment]
Это не критично, не думаю, что когда-то дойдёт спор за цену до 1-2 центов)

**Comment by SnaiCrys** [comment]
когда то поправлю
