### ISSUE TITLE
Новые заправки, палатки с едой, автоматы еды и прочее

### ISSUE THREAD

**Issue by GomeshRu** [SnaiCrys/BUG-TRACKER#137]
Маркеры для новых заправок:
175.9972076416,-1561.7680664062,29.261720657348   заправка рядом с гето
Продуктовые лавки, аппараты с газировкой и едой
2477.5966796875,4445.9653320312,35.336948394776 Продуктовая лавка
1699.6040039062,4791.662109375,41.922374725342 Газировочка автоматы
1047.9497070312,2662.728515625,39.551124572754 Чипсы и снеки автоматы
19.864252090454,-1114.0710449218,29.79702949524 Газировочка
1726.2023925782,6412.1640625,35.000652313232 автомат газировки (правое шоссе)
1587.7662353516,6449.7583007812,25.317140579224 автомат газировки (правое шоссе)
-2507.7119140625,3614.0886230468,13.814178466796 фрукты (левое шоссе)
549.04193115234,2674.8059082032,42.19951248169 автомат газировки (сэнди шорс)
1047.6057128906,2662.7268066406,39.551136016846 автомат еды (сэнди шорс)
1193.3468017578,2701.6750488282,38.159404754638 автомат газировки (сэнди шорс)
-1385.1591796875,737.61944580078,182.9448852539   фрукты

Заправка
-319.46337890625,-1471.1361083984,30.548385620118  -заправка рядом с салоном бенни        

1785.9538574218,3330.8552246094,41.379745483398
Заправка без маркеров и блипа

1474.6612548828,2725.6469726562,37.662143707276  -палатка с едой

не видно маркер на добыче минералов   2965.4475097656,2747.8869628906,43.30668258667

можно убрать 3 блипа на минералах, оставив лишь этот 2975.4689941406,2782.5732421875,38.980926513672
Добавить на заводе контейнер  1074.1749267578,-2009.9421386718,32.084953308106
Добавить на заводе гараж для машин  1074.262084961,-1950.8081054688,31.01424407959
Добавить контейнер для песка на 500 кг 2699.7297363282,2773.2199707032,37.878036499024
Увеличить контейнер у шахты до 1000 кг  -600.59326171875,2089.2397460938,132.41821289062

**Comment by Fleki** [comment]
-38.09557723999,-1094.2921142578,26.422338485718 Кофейный автомат у автоваза

**Comment by Budzzza** [comment]
Магазины оружия:
-664.01470947266,-947.12670898438,21.59518623352
242.90202331542,-43.686546325684,69.896598815918
Водохранилище, вариант добычи грязной воды:
1025.9210205078,-654.16613769532,58.51187133789
1252.8037109375,-1062.8079833984,41.949493408204
32.027431488038,856.1929321289,197.73477172852
Тату центр с интерьером внутри:
1320.5604248046,-1647.8000488282,52.145584106446
При имплементации медицинской марихуаны можно использовать этот магазин для продажи:
-1174.3685302734,-1573.2142333984,4.3686146736146
Прокат велосипедов (рядом есть банкомат):
-1105.58203125,-1693.548461914,4.3625164031982

**Comment by Budzzza** [comment]
Водохранилище, вариант добычи грязной воды:
1025.9210205078,-654.16613769532,58.51187133789

**Comment by Budzzza** [comment]
1084.3450927734,-773.5053100586,58.061305999756 (автоматы снэков и напитков около банкомата и покупки машин)
-1195.7824707032,-1544.8153076172,4.369966506958 (закусочная около пляжа, рядом с качалкой)

**Comment by Budzzza** [comment]
1473.8319091796,2725.6232910156,37.660614013672 - лавка фруктов на дороге

**Comment by denden125** [comment]
-325.50439453125,-738.50329589844,33.964073181152 автомат с колой на автостоянке

**Comment by denden125** [comment]
-551.84643554688,-854.83294677734,28.188159942626 магазин с едой на Бульвар Веспуччи

**Comment by denden125** [comment]
169.55772399902,-1566.5544433594,29.288412094116 заправка рядом с больницей нет на карте и нет 
 функционала

**Comment by Fleki** [comment]
-92.668449401856,6409.8520507812,31.640367507934 Продуктовый на заправке в Палетто

**Comment by Fleki** [comment]
1712.271484375,2703.8110351562,-73.417106628418 Автомат с едой в Федеральной Тюрьме

**Comment by Fleki** [comment]
449.82434082032,-987.85809326172,26.674234390258 Кофейный аппарат в ЛСПД
