### ISSUE TITLE
Пропажа миссий механика

### ISSUE THREAD

**Issue by NoblePostman** [SnaiCrys/BUG-TRACKER#14]
пропали миссии механика, не появляются в течении 2-х часов, вместо маркеров на карте и сводки задания - черный квадратик в верхнем правом углу
![image](https://user-images.githubusercontent.com/32131843/30644356-c9320ce2-9e1a-11e7-98e9-06c919d0fd40.png)

**Comment by dotpixel** [comment]
Пофикшено.
