### ISSUE TITLE
Не отображаемые метки на карте\на земле

### ISSUE THREAD

**Issue by Budzzza** [SnaiCrys/BUG-TRACKER#140]
# На земле:
Метки в воде не отображаются:
644.56634521484,-1830.0454101562,9.0226697921752 - Канал, скутера
1427.9107666016,3818.0656738282,31.586771011352 - Сэнди шорс, скутера

# На карте:
944.32141113282,-1453.1563720704,31.13842201233 - Огромная мастерская, где внутри ничего нету.
* заметка: внутри есть дверь, которая открывается на лестничную клетку, но пройти туда нельзя

**Comment by TechnicolorII** [comment]
Если в воду ставить маркеры, то они так и работают, соррян, по-другому никак.
