### ISSUE TITLE
кротовая нора через пол штата

### ISSUE THREAD

**Issue by GomeshRu** [SnaiCrys/BUG-TRACKER#157]
-1146.0694580078,4961.8203125,221.03688049316  -маркер входа в подвал
попадаем вот сюда 1066.2506103516,-3183.6103515625,-39.163639068604
но из помещения есть еще один выход 1039.6115722656,-3196.111328125,-38.168746948242
-51.256004333496,1910.9112548828,195.35820007324  -вот второй выход
![20180319001901_1](https://user-images.githubusercontent.com/37335697/37571280-a625e506-2b0b-11e8-8e19-3507c36dce60.jpg)
![20180319002016_1](https://user-images.githubusercontent.com/37335697/37571282-b037ef76-2b0b-11e8-8b08-b6679aa73b9e.jpg)
![20180319002317_1](https://user-images.githubusercontent.com/37335697/37571285-bc0bc39a-2b0b-11e8-8f54-d7670d9f581a.jpg)

**Comment by SnaiCrys** [comment]
это интерстелар

**Comment by UncleJust** [comment]
так и задумано
