### ISSUE TITLE
NPC выкупает бензин как и раньше (АЗС)

### ISSUE THREAD

**Issue by coder-m1ckey** [SnaiCrys/BUG-TRACKER#160]
Выставил бензин по 0.90 в магазин АЗС, пришло уже 2ое оповещение что вы продали бензин. На заправке щас по 0.7 , с заправки никак не могли покупать. Врядли покупали и с магазина АЗС, кому надо покупать по 0.9 когда есть по 0.7?

https://imgur.com/a/uiEPM

**Comment by SnaiCrys** [comment]
все правильно
