### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by AlexandrGTrigger** [SnaiCrys/BUG-TRACKER#186]
Перенести маркер "Магазин(Магазин чертежей автомобилей)
Отсюда:
![image](https://user-images.githubusercontent.com/37502544/37648865-cd0837e0-2c38-11e8-9cf4-09176b16b0fc.png)
722.26208496094,-1069.7376708984,23.062395095826
Сюда:
![image](https://user-images.githubusercontent.com/37502544/37648921-f6c28720-2c38-11e8-90ad-57459222a9e6.png)
725.82244873046,-1070.8935546875,28.311012268066

**Comment by TechnicolorII** [comment]
Не стоит, этот гараж может быть частной территорией
