### ISSUE TITLE
Добавить АЗС

### ISSUE THREAD

**Issue by AlexandrGTrigger** [SnaiCrys/BUG-TRACKER#188]
Добавить АЗС на Эль-Бурро-Хайтс:
![image](https://user-images.githubusercontent.com/37502544/37652756-46346718-2c45-11e8-9cea-508992cbfe8a.png)
Маркер 1242.8428955078,-1487.2023925782,34.692569732666

**Comment by TechnicolorII** [comment]
Рядом есть заправка. Лучше карту не захламлять блипами.
