### ISSUE TITLE
Недвижимость Innosens на Ранчо

### ISSUE THREAD

**Issue by AlexandrGTrigger** [SnaiCrys/BUG-TRACKER#189]
Стоимость недвижимости 300$; Должно было быть 3000$
![image](https://user-images.githubusercontent.com/37502544/37651829-2260e314-2c42-11e8-920d-2465372abc75.png)
Продажа недвижимость 0$; Должно было быть 2500$
![image](https://user-images.githubusercontent.com/37502544/37652883-a9dd62d8-2c45-11e8-93df-7efd641d5a81.png)
570.90246582032,-1746.460571289,29.227815628052

**Comment by TechnicolorII** [comment]
Не, так и задумано всё. Это мотель
