### ISSUE TITLE
Заниматься бензином не выгодно

### ISSUE THREAD

**Issue by coder-m1ckey** [SnaiCrys/BUG-TRACKER#198]
Допустим я потратил на бензин 0.74 за еденицу (хотя фактически я потратил больше, я брал товары с порта) , завез в АЗС 767 едениц бенза, сижу и думаю нужно отдохнуть пойти поРПшить и пожить городской жизнью без фарма пока бензин скупят. Вижу что скупили бенз на сумму 105$ , еду на хранилище и вижу такую картину - остается 554. Включаю математика, считаю 767-554=203. 203 еденицы бенза за 105 баксов? По 0.5? Карл, я потратил на изготовление больше.

Я предлагаю убрать скупку бензина для нпц или пускай они скупают по цене для игроков. По 10-20 бенза чтобы зарабатывать тупо на НПЦ (и опять же выше себестоимости ты не получишь) заливать можно целый день и забыть про РП вообще. 

Эта система выгодна если ты не тратишь бабки на ресурс, выгодно продавать так нефть через молл. 

"Почему нет в штате бензина?" потому что его весь скупают НПЦ за бесценок, вгоняют нефтянников в минус и отбивают желание им вообще заниматься. Нужно с этим что то делать.

**Comment by SnaiCrys** [comment]
По цене игроков? А если ты поставил 500 баксов?

**Comment by coder-m1ckey** [comment]
Вот и я про то же, значит нужен банк какой то у нпц, чтобы в реальные сутки они могли скупать не более чем на 1000 долларов бензина , то есть НПЦ 1 раз за сутки может выкупить за 1к 1 еденицу бензина, или по 10$ 100 раз.

**Comment by SnaiCrys** [comment]
Мы делаем бензохранилище вам которое привязано к заправкам где игроки покупают по вашей цене + молл где нпс скупают.
Сами решать будете куда сбрасывать бенз
