### ISSUE TITLE
Неверное название авто в магазине

### ISSUE THREAD

**Issue by Maru4eckuu3auka** [SnaiCrys/BUG-TRACKER#2]
![12312312312312311232](https://user-images.githubusercontent.com/32035628/30521152-11380aec-9be5-11e7-9fa1-ae1d9709dce7.jpg)
В магазине маслкаров есть несоответствие в названии авто.
В списке авто есть пункт "Feltzer", однако на самом деле продаётся "Stirling GT" и изображение от "Stirling GT"

**Comment by SnaiCrys** [comment]
Исправлено
