### ISSUE TITLE
Баг с инвестициями

### ISSUE THREAD

**Issue by Budzzza** [SnaiCrys/BUG-TRACKER#211]
Когда накапливается определенная сумма денег (прибыль с инвестиций), то ее снимая прибыль получается дюп - если прокликать "Снять прибыль" через "Enter" несколько раз, то прибыль дюпается и синмается несколько раз (у меня получилось х3 с моей прибыли).
Инвестировал в магазин сигар: -270.01501464844,246.48983764648,90.341613769532

**Comment by SnaiCrys** [comment]
после след рестарта проверить еще раз
