### ISSUE TITLE
Уведомления (Баланс банковского счета,цена покупки и т.д.)

### ISSUE THREAD

**Issue by 90noname90** [SnaiCrys/BUG-TRACKER#213]
1.В уведомлениях показывает старый баланс банковского счета(по факту баланс моего счета 700$+)
2.В магазине 24/7 ,при покупке товара на сумму 30$+ , показало стоимость покупки "Оплачено 199.98$"
3. Уведомления не пропадают,так и висят все время.
Скрин уведомлений
https://c.radikal.ru/c05/1803/fa/dd4455c0df6f.jpg

**Comment by SnaiCrys** [comment]
нужно всегда перезаходить в игру после выхода с сервера. это баг gui
