### ISSUE TITLE
Баг с маркером гаража грузовиков в порту

### ISSUE THREAD

**Issue by lavrentiy63** [SnaiCrys/BUG-TRACKER#220]
Если подъехать на машине в маркер, дождаться открытия меню и выйти из машины клавишей F, то машина пропадет.

**Comment by SnaiCrys** [comment]
звучит странно, надо проверить еще раз

**Comment by SnaiCrys** [comment]
попробовал, ничего подобного не случилось. пока закрою тикет. если будет что то еще раз подобное, описать сюда же

**Comment by lavrentiy63** [comment]
Только что снова попробовал и машина исчезла.

**Comment by SnaiCrys** [comment]
машина куплена в этом гараже?
джойстик или клавиатура во время езды?

**Comment by lavrentiy63** [comment]
Машина просто рандомная с улицы, клавиатура.

**Comment by lavrentiy63** [comment]
https://www.twitch.tv/videos/241864250
сделал запись, чтобы понятней было.
