### ISSUE TITLE
Резиновые карманы через обыск

### ISSUE THREAD

**Issue by coder-m1ckey** [SnaiCrys/BUG-TRACKER#225]
Если через обыск забирать предметы у человека можно забрать сколько угодно и перезабить свой инвентарь хоть до 1000.0/26.32 То есть при макс. весе 10.0/10.0 можно через обыск взять любой предмет у человека, хотя через "передать" будет писать что инвентарь заполнен.

**Comment by SnaiCrys** [comment]
должно быть исправлено
