### ISSUE TITLE
Все еще можно фармить оружие с нпц

### ISSUE THREAD

**Issue by Banan420** [SnaiCrys/BUG-TRACKER#246]
В гольф клубе с неписей выпадают клюшки. Достаточно слегка их толкнуть 
-1324.2570800782,49.48010635376,53.53815460205

**Comment by SnaiCrys** [comment]
поправил, надо проверить после рестарта

**Comment by Banan420** [comment]
Рестарт был, все еще выпадают.

**Comment by SnaiCrys** [comment]
А пистолеты с черных ребят?
