### ISSUE TITLE
координаты

### ISSUE THREAD

**Issue by goldnastya** [SnaiCrys/BUG-TRACKER#266]
-1684.8344726562,-1125.2169189454,13.152177810668 - сделать покупку хотдогов
-1721.7342529296,-1102.728881836,13.075947761536
-1773.5362548828,-1159.7307128906,13.018023490906
-1636.387084961,-1083.8884277344,13.058780670166
-1515.2904052734,-950.18078613282,9.3728713989258
240.70487976074,164.8648071289,105.0503616333

-1694.997680664,-1126.4086914062,13.15228176117 - автомат напитков
-1692.3099365234,-1087.9776611328,13.152926445008

-1692.5499267578,-1134.0135498046,13.152430534362 - сделать покупку бургеров
-1786.5551757812,-1174.3215332032,13.017664909362
-1855.2067871094,-1222.4851074218,13.017223358154
245.59312438964,164.20899963378,104.968460083
405.72457885742,105.0884475708,101.32164764404
-1182.0437011718,-882.91955566406,13.794695854188 - большой магазин бургершот

-1693.4841308594,-1123.3806152344,13.152280807496 - автомат с вредной едой

-1695.4913330078,-1071.355102539,13.114171028138 - убрать из продажи фишбургер

-38.193965911866,-1094.6021728516,26.42234992981 - автомат с кофе

![image](https://user-images.githubusercontent.com/37379018/38095279-b9bb8312-3378-11e8-811e-2f9ae02853ab.png) не работает картинка

**Comment by TechnicolorII** [comment]
Несколько расставил, слишком много не стоит
