### ISSUE TITLE
Абуз на мусоре

### ISSUE THREAD

**Issue by Banan420** [SnaiCrys/BUG-TRACKER#274]
В обычных условиях мусорщик на точке выгрузки мусора не может двигаться и выходить из машины. Но если за рулем другой человек, то он может проехать по метке хоть 5 раз, при этом не застревая. Так можно проехав несколько раз по одной точке сразу выполнить миссию. И также можно получить  оплату несколько раз на одно задание.

**Comment by SnaiCrys** [comment]
Сделать так чтобы только водитель мог выполнять?

**Comment by Banan420** [comment]
Получается да, или чтоб все в этих маркерах застревали, но первое наверно проще сделать. 
Или еще сделать так, чтоб одну и ту же точку больше 1 раза использовать было невозможно. Или сделать разгрузку моментальной, чтоб точка сразу пропадала
