### ISSUE TITLE
Не рабочий маркер на базе механиков

### ISSUE THREAD

**Issue by KononoffKirill** [SnaiCrys/BUG-TRACKER#287]
Маркер по координатам 727.64227294922,-1067.195678711,28.311014175416 не работает, подозрения на то, что там должны быть инвестиции, но у меня есть и права механика и лидерка, так я являюсь механиком и лидером шахтёров, но мне не показывает, что на этом маркере что-либо есть. Рядом маркер контейнера.
![image](https://user-images.githubusercontent.com/34405038/38210972-a84152c8-36c1-11e8-95fe-11795c6e891c.png)

**Comment by TechnicolorII** [comment]
Это отдельная инвестиция для владельцев именно этого лск.
