### ISSUE TITLE
Баг с квартирой.

### ISSUE THREAD

**Issue by Psucho9111** [SnaiCrys/BUG-TRACKER#296]
![dom 3](https://user-images.githubusercontent.com/38052478/38273498-c5e2fc68-3794-11e8-8a3b-9ccf337053c2.png)
![dom](https://user-images.githubusercontent.com/38052478/38273499-c60778ea-3794-11e8-96bc-9feb5fa052a5.png)
![dom 1](https://user-images.githubusercontent.com/38052478/38273500-c62c35f4-3794-11e8-80ec-af530826e26b.png)
Не могу войти в свой дом, пишет что не мой, продать тоже не могу. Перезаход не помогает.

**Comment by KononoffKirill** [comment]
Прикольно, что в пасспорте написано paleto house 9, а сам адрес дома paleto drive 9
