### ISSUE TITLE
Баг с получением звёзд розыска со своим авто

### ISSUE THREAD

**Issue by Maru4eckuu3auka** [SnaiCrys/BUG-TRACKER#3]
Чиркану, чтобы не забыли.
Когда садишься в свою машину с пассажирского сиденья - получаешь 2 звезды розыска.
+Когда машину закрываешь на ключ и пытаешься сесть - тоже получаешь 2 звезды розыска

**Comment by SnaiCrys** [comment]
Фикс готов, будет после рестарта.
