### ISSUE TITLE
Аппарат отпечатков пальцев

### ISSUE THREAD

**Issue by Silence02** [SnaiCrys/BUG-TRACKER#304]
Не работает аппарат отпечатков пальцев у медиков

**Comment by XtinaTV** [comment]
Аппарат отпечатков пальцев доступен только полицейским

**Comment by Silence02** [comment]
Я имел ввиду про лабораторию у медиков. Не работает у них, когда пытаюсь узнать отпечатки пальцев

**Comment by coder-m1ckey** [comment]
Всё там работает. Сначала снимаем отпечатки пальцев с предмета на земле, получаем в инвентарь слепок отпечатков, их везем в лабу медикам и получаем результат.
