### ISSUE TITLE
Клюшка для гольфа не продается

### ISSUE THREAD

**Issue by Wlwool** [SnaiCrys/BUG-TRACKER#309]
В молле не продается клюшка для гольфа ни за какую цену, НПС не покупают, а рекомендованая цена 0 баксов
![2018-04-08_09-19-29](https://user-images.githubusercontent.com/37796420/38463977-263b2ef6-3b0e-11e8-80d6-36c695ad6b4c.png)

**Comment by TechnicolorII** [comment]
Так и должно быть, чтобы не было абуза оружия с нпс.
