### ISSUE TITLE
Идея: удаление сохраненных скинов

### ISSUE THREAD

**Issue by cryptohyde** [SnaiCrys/BUG-TRACKER#31]
У многих игроков возникает проблема с сохраненными скинами: при смене персонажа, например, предыдущие "луки" уже не нужны, а удалить их возможности нет, в итоге они накапливаются и занимают место. Поэтому предлагаю ввести функционал по удалению сохраненной одежды.

**Comment by SnaiCrys** [comment]
Сделано
