### ISSUE TITLE
Много всего!

### ISSUE THREAD

**Issue by pycu** [SnaiCrys/BUG-TRACKER#311]
1 Джип fq2 можно взять только в гараже джипов, дома не показывает ее
так же показывает что она 90кг на самом деле 20кг!
2 Все оружие у мафии не работает, то есть патроны не подходят к оружию! но подходящие могут прописать кураторы и допустим каждый раз делать обмен людям, пока не пофиксят я думаю это самый правильный  вариант решить эту проблему!
3Коктейли молотова можно делать только патроны, а вот штуки в которую их заряжают ни где не сделать! даже у оружейников!
4 у оружейников проблема с АКСУ так же патроны для АКСУ не подходят и решить это могут кураторы прописав их!
5 Сделал 3 оружия вчера, вчера же пропал одна единица думаю может в другую машину положил, сегодня пропала еще одна! все облазил ни где нет(это было недельку назад) заметил такую пропажу только на томсонах

**Comment by TechnicolorII** [comment]
Если патроны из магазина не подходят к оружию мафии, то понятно в чём проблема. Решил, зальём апдейт - попробуйте и отпишитесь сюда.

**Comment by pycu** [comment]
Мафия может крафтить оружие и патроны к нему, вот патроны не подходят! А Аксу это у оружейников и там такая же проблема
Это после рестарта проверять?

**Comment by pycu** [comment]
и как узнать когда апдейт будет залит? куда отпишите?
