### ISSUE TITLE
Прицепы по 10 $

### ISSUE THREAD

**Issue by Maru4eckuu3auka** [SnaiCrys/BUG-TRACKER#4]
![000](https://user-images.githubusercontent.com/32035628/30521412-97bba71e-9be9-11e7-98c2-5067b4953025.jpg)
Еще темку, чтобы не забыли, пофиксить вместительные прицепы по 10 $

**Comment by SnaiCrys** [comment]
Исправлено

**Comment by RockIsLife** [comment]
А тягач за $10000 его нормальная цена?
