### ISSUE TITLE
Имбовая рыба.

### ISSUE THREAD

**Issue by MartinElbrus** [SnaiCrys/BUG-TRACKER#59]
При ловле рыбы нет расходным материалов. Была идея при разговоре, чтобы расходовалась наживка, можно растительная (кукуруза или иное). Или сделать откат жарки на кострах до 10 минут и сделать не больше 2х рыб на один костер. Первый вариант предпочтительней.

Как сейчас: выловив 10 рыбы, идем жарить на костер - получаем жаренную рыбу, не расходуя ничего. Никто из профессий не нужен. Имба.

**Comment by TechnicolorII** [comment]
Пока пофиксил костры, с наживкой интересная идея
