### ISSUE TITLE
Покупка выложенного товара.

### ISSUE THREAD

**Issue by MartinElbrus** [SnaiCrys/BUG-TRACKER#60]
После выкладки товара в магазин (например, водка), при его покупке приходит оповещение владельцу о приобретении, покупателю же **не сообщается об удачном приобретении (оповещение) и товар не попадает в инвентарь покупателя**. Со склада удаляется приобретенное количество, в счет владельца товара деньги поступают.

**Comment by SnaiCrys** [comment]
исправлено
