### ISSUE TITLE
Бесплатная заправка.

### ISSUE THREAD

**Issue by WeIIing** [SnaiCrys/BUG-TRACKER#61]
Подъезжаешь и начинаешь заправку. Примерно к середине, глушишь и заводишь двигатель, выходя из машины и отбегая от неё. Возвращаешься и садишься, заводя её. Идёт оповещение, о заправке на ($), а деньги не списываются и ты спокойно едешь, заправившись и оставив деньги при себе.

**Comment by SnaiCrys** [comment]
они списались в момент прожатия меню
исправлен нотификейшн
