### ISSUE TITLE
Баг с заправкой

### ISSUE THREAD

**Issue by iClevery** [SnaiCrys/BUG-TRACKER#64]
Так как заправка теперь работает через меню, появился новый баг. Если встать на место заправки и сразу отъехать, ничего не нажимая, то меню с заправкой не пропадёт (возможно оно вообще не пропадает при любом условии). После этого можно заправить автомобиль в любом месте, хоть в километре от заправки.

**Comment by SnaiCrys** [comment]
надо понять при каком условии не пропадает

**Comment by iClevery** [comment]
Я просто вставал на метку и уезжал - меню оставалось висеть. Сегодня ещё почекаю.

**Comment by GandiTheCrocodale** [comment]
Метка не пропадает, если встать на 2 метки или быстро уехать с 1 или 2х меток.

**Comment by koshkva** [comment]
![20180315194655_1](https://user-images.githubusercontent.com/37342750/37456129-681ed11a-288a-11e8-8b37-cf44ee274fa5.jpg)

**Comment by SnaiCrys** [comment]
Проверьте тот же баг с автомойкой

**Comment by SnaiCrys** [comment]
добавил проверку на дистанцию
