### ISSUE TITLE
Поднятие предметов + предложение по улучшению.

### ISSUE THREAD

**Issue by undefinedprsn** [SnaiCrys/BUG-TRACKER#75]
1.При поднятии предметов с земли, в окне поднятия отображается количество этого предмета в инвентаре, а не количество предмета, доступного для поднятия (Что было бы логично).
https://imgur.com/0VlQHja
https://imgur.com/QXtMrLj
https://imgur.com/bYrjgC7
2.В связи с увеличением веса предмета "Древесный уголь", объем склада в 750кг стал слишком мал. Если нет возможности увеличить склад, то добавить пару - тройку складов рядом. 
3.Предметы не удаляются из инвентаря передающего игрока при передаче/складировании
https://imgur.com/bYrjgC7

**Comment by SnaiCrys** [comment]
3 пункт буду править позже
