### ISSUE TITLE
Рыбалка и костёр

### ISSUE THREAD

**Issue by PurpleDrunk** [SnaiCrys/BUG-TRACKER#77]
На данных координатах находится 2 костра, один не работает. 
-832.32775878906,5892.60546875,6.0076622962952

Рыбалка, когда ловишь морепродукты или водоросли выскакивает окно "Поймал рыбу" , надо удалить это окошко прилагаю скрин. 
![unknown 1](https://user-images.githubusercontent.com/37342777/37431938-17231432-27f0-11e8-91ac-8f17905ba28e.png)

**Comment by TechnicolorII** [comment]
Костёр лучше один оставить, а то вчера жаловались что они имбовые. Уведомление заменил на более нейтральное.
