### ISSUE TITLE
Выставление цены на товар

### ISSUE THREAD

**Issue by undefinedprsn** [SnaiCrys/BUG-TRACKER#78]
Если выставить товар за цену, затем забрать его и снова попытаться поставить по другой цене - выскакивает окно "У вас уже выставлен этот товар на продажу по другой цене", что делает невозможным изменение цены.
https://imgur.com/haJq5AR

**Comment by ISKANDER499** [comment]
Добавлю больше. Когда товар заканчивается, он все равно остается в Молле с количеством в ноль.
Так же при выставлении бензина есть такой ньюанс. Например было выставлено 500 бензина по 1$ и 10 бензина по 0.50$, на АЗС будет предлагать купить бензин за 0.50, но если в бак нужно больше 10 литров, то колонка в обще ни чего не заправит. Сейчас на сервере есть 1000 бензина за 0.70$ и ноль бензина за 0.68$.  Но на АЗС предлагает заправится за 0.68, а при подтверждении соответственно пишет что бензина нет.
