### ISSUE TITLE
Перегон нефти в бензин и пару предложений.

### ISSUE THREAD

**Issue by ISKANDER499** [SnaiCrys/BUG-TRACKER#85]
История такова. Нефтяник собирает нефть руками, кладет в машину, из машины в руки, перегоняет в бензин с X10 на выходе(1 нефть =10 бензина(1 нефть=1кг, 1 бензин=1кг)), руками кладет в машину с большим объемом багажника, из машины руками несет в Молл. На то что бы перетащить из цистерны 1000 бензина по 26 бензина в Молл, нужно не меньше 40 минут тыканья тильды. Думаю у других проф похожая ситуация. 
Собственно идеи/предложения таковы.
Для Нефтяников
Переработать понятие нефти и бензина, перенос/перевоз осуществляется либо в канистре, либо в автоцистерне. При добыче нефти заливать ее сразу в автоцистерну. При переработке в бензин, нефть заливать в резервуар и через какое то время перекачивать в автоцистерну бензин, либо по КД в самой автоцистерне перегонять нефть в бензин. Так же лидеру фракции дать право единолично выставлять цену в Молле/городе на бензин/товары, а сотрудники фракции могут только пополнять его количество.
Для других фракций ввести перегон ресурсов из склада/точки в машину/склад например через автопогрузчик.

**Comment by ISKANDER499** [comment]
123

**Comment by TechnicolorII** [comment]
В текущих реалиях снизили вес нефти, с разделением ролей ничего сделать не можем
