### ISSUE TITLE
Магазин механиков

### ISSUE THREAD

**Issue by SnaiCrys** [SnaiCrys/BUG-TRACKER#92]
Сделать крафт запчастей разных типов (фары, зеркала, свечи зажигания, форсунки, фильтры) для продажи НПС

**Comment by TechnicolorII** [comment]
Вы и так можете продавать детали низкого качества нпс.

**Comment by SnaiCrys** [comment]
Я Кандидат, я прошу сделать

**Comment by TechnicolorII** [comment]
Сделаю
