### ISSUE TITLE
Триггер Магазина в любом месте.

### ISSUE THREAD

**Issue by GandiTheCrocodale** [SnaiCrys/BUG-TRACKER#95]
Если быстро проехать по триггеру и нажать enter, то можно в любом месте закинуть товар в магазин. Тоже самое со всеми ящиками.
![image](https://user-images.githubusercontent.com/37401065/37462211-2cd6ce64-2862-11e8-94b4-8f90bd56824e.png)

**Comment by SnaiCrys** [comment]
сделал проверку на дистанцию
